baseURL = 'https://keimei-skizzen.org/'  # 这里写你的自定义域名
languageCode = 'zh-cn'
title = 'Keimei Skizzen' # 你的博客标题
theme = 'PaperMod'

[params]
    env = "production"
    title = "Keimei Skizzen"
    description = "关于哲学的随笔与思考"
    author = "ASAMORI KEIMEI"
    
    # 首页配置
    [params.homeInfoParams]
        Title = "旭森景明の場所"
        Content = "欢迎来到我的场所。这里记录着关于生活，哲学与观察的一些巧思。"
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/ASAMORI-KEIMEI"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:contact@keimei-skizzen.org "
    # 菜单配置
    [[menu.main]]
        identifier = "posts"
        name = "文章"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "categories"
        name = "分类"
        url = "/categories/"
        weight = 20

    [[menu.main]]
        identifier = "tags"
        name = "标签"
        url = "/tags/"
        weight = 30